name: Amanda Lam
markdown: kramdown
theme:
gems: 
 - jekyll-paginate-v2
exclude:
 - Gemfile
 - Gemfile.lock
permalink: /:year/:month/:title.html
############
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

title: Data Blog
author: Amanda Lam
description: >           
  Test
slogan: hello      
#avatar: /i/avatar.png    
#banner: /i/mountains.svg 
baseurl: 
repo: https://github.com//rlue.github.io # appears in footer

nav_menu:
  - name: About
    url: /
    #icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Resume
    url: /
    #icon: /i/icons.svg#portfolio
  - name: Archive
    url: /posts
    #icon: 
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    #icon: /i/icons.svg#email
