name: Amanda Lam
markdown: kramdown
theme:
gems: 
 - jekyll-paginate-v2
exclude:
 - Gemfile
 - Gemfile.lock
permalink: /:year/:month/:title.html
############
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

