#######################
# Theme Customization #
#######################

title: Amanda Lam        # appears in the header and the HTML <title> tag
author: Amanda Lam    
slogan: Data Blog      
avatar: /i/avatar.jpg    # appears as portrait in the header
banner: /i/mountains.svg # appears as background in the header
repo: https://github.com//rlue.github.io # appears in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Home
    url: /
    icon: /i/icons.svg#Home
  - name: About
    url: 
    icon: /i/icons.svg#About
  - name: Posts
    url: /post
    icon: /i/icons.svg#posts 
  - name: Resume
    url:  
    icon: /i/icons.svg#Resume
  

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
