#######################
# Theme Customization #
#######################

title: Amanda Lam        
author: Amanda Lam    
slogan: Data Blog      
avatar: /i/avatar.jpg    
banner: /i/banner2.jpg 

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Home
    url: /
    icon: /i/icons.svg#Home
  - name: About
    url: /about
    icon: /i/icons.svg#About
  - name: Archive
    url: /post
    icon: /i/icons.svg#Archive 
  - name: Resume
    url:  /resume
    icon: /i/icons.svg#Resume
  

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
